### PR TITLE
Fix get_user API endpoint

### PR DESCRIPTION
**Pull request by 75efb6**
Fixed (I think) by removing .as_json() and using jsonify instead as it was giving me an error related with that

### CODE REVIEW

**Comment by 75efb6** [comment]
Still not working, now gives "TypeError: Object of type Player is not JSON serializable" error

**Comment by 75efb6** [comment]
Using as_json() gives this error "TypeError: 'dict' object is not callable"

**Comment by 75efb6** [comment]
Closed by accident lol 😂

**Comment by 75efb6** [comment]
Ok, I fixed it now by using as_json without (), that's what happens when you don't test a "fix", this one is tested working

**Comment by unclem2** [comment]
Thanks for contribution. Merged

**Pull request merged**
